version: "3"
services:
  elastic:
    build: 
      context: .
      dockerfile: Dockerfile-elastic
    image: elastic2.2:2.2
    ports:
      - "9200:9200"
      - "9300:9300"
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile-rabbitmq
    image: rabbitmq:rq
    ports:
      - "5672:5672"
      - "15672:15672"
