<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="registration" nsURI="http://org.pprls/registration/1.0" nsPrefix="org.pprls.registration">
  <eClassifiers xsi:type="ecore:EEnum" name="FileType">
    <eLiterals name="PDF"/>
    <eLiterals name="DOC" value="1"/>
    <eLiterals name="DOCX" value="8"/>
    <eLiterals name="ODT" value="2"/>
    <eLiterals name="TXT" value="3"/>
    <eLiterals name="RTF" value="4"/>
    <eLiterals name="XLS" value="5"/>
    <eLiterals name="XLSX" value="7"/>
    <eLiterals name="ODS" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Year">
    <eLiterals name="ANY" literal="ANY"/>
    <eLiterals name="YEAR_EPOCH" value="1970" literal="1970"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Correspondent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vatId" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comments" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postageinfo" eType="#//PostageInfo"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recipientType" eType="#//CorespondentType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phones" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        defaultValueLiteral="">
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="@OneToMany(fetch=EAGER)&#xD;&#xA;@Fetch(FetchMode.JOIN)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="registryNumber" eType="#//SenderRegistryNumber"
        unsettable="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entitydescriptor" eType="#//EntityDescriptor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DocumentType">
    <eLiterals name="NOTE" literal="Σημείωμα"/>
    <eLiterals name="DOCUMENT" value="1" literal="Έγγραφο"/>
    <eLiterals name="EMAIL" value="2" literal="email"/>
    <eLiterals name="SMS" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PostalMethod">
    <eLiterals name="Other" literal=""/>
    <eLiterals name="SnailMail" value="1" literal="ΕΛΤΑ"/>
    <eLiterals name="Fax" value="2"/>
    <eLiterals name="Email" value="3"/>
    <eLiterals name="HandDelivered" value="4" literal="Ιδιοχείρως"/>
    <eLiterals name="Digital" value="5" literal="Ψηφιακά"/>
    <eLiterals name="RegisteredSnailMail" value="6" literal="Συστημένο"/>
    <eLiterals name="Courier" value="7"/>
    <eLiterals name="Empowerment" value="8" literal="Eξουσιοδότηση"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Outgoing" eSuperTypes="#//RegistryRecord">
    <eOperations name="getBasicEditor" lowerBound="1" eType="#//EntityDescriptor"/>
    <eOperations name="isSigned" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eOperations name="reissue" eType="#//Outgoing"/>
    <eOperations name="getState" eType="#//DocumentStatus"/>
    <eOperations name="close">
      <eParameters name="handler" eType="#//EntityDescriptor"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfRepeats" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int" defaultValueLiteral="0"
        derived="true">
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value=" @Formula(&quot;(select count(*) from Outgoing o where o.outgoing_reissued_e_id=e_id)&quot;)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="issuer" lowerBound="1"
        upperBound="-1" eType="#//EntityDescriptor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editor" lowerBound="1"
        upperBound="-1" eType="#//EntityDescriptor" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reissued" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedIncoming" eType="#//Incoming"
        resolveProxies="false">
      <eAnnotations source="teneo.jpa"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Incoming" eSuperTypes="#//RegistryRecord">
    <eOperations name="reply" lowerBound="1" eType="#//Outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRelated" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="relatedToOutgoing"/>
      </eAnnotations>
      <eAnnotations source="teneo.jpa">
        <details key="value" value="@Type(type = &quot;org.hibernate.type.NumericBooleanType&quot;)"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DocumentStatus">
    <eLiterals name="ACCEPTED" value="2" literal="Αποδεκτό"/>
    <eLiterals name="DONE" value="10" literal="Ολοκληρωμένο"/>
    <eLiterals name="ARCHIVED" value="11" literal="Αρχειοθετημένο"/>
    <eLiterals name="REJECTED" value="3" literal="Απορριφθέν"/>
    <eLiterals name="CANCELLED" literal="Ακυρωμένο"/>
    <eLiterals name="PENDING" value="1" literal="Σε αναμονή"/>
    <eLiterals name="UNDER_REVISION" value="4" literal="Σε αναθεώρηση"/>
    <eLiterals name="START" value="5" literal="Έναρξη"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatusHistory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logMessage" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="incoming_thread_e_id" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Short" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="status" lowerBound="1"
        eType="#//Status" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DocumentOperations">
    <eLiterals name="ASSIGN" literal="Ανάθεση"/>
    <eLiterals name="CANCEL" value="1" literal="Ακύρωση"/>
    <eLiterals name="REJECT" value="2" literal="Απόρριψη"/>
    <eLiterals name="COMPLETE" value="3" literal="Ολοκλήρωση"/>
    <eLiterals name="REVERT" value="4" literal="Ανάκληση"/>
    <eLiterals name="ARCHIVE" value="5" literal="Αρχειοθέτηση"/>
    <eLiterals name="ACCEPT" value="6" literal="Αποδοχή"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Producer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Class that represents a producer. The data from this comes from the BI"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstname" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastname" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="afm" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        defaultValueLiteral="">
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="@NaturalId"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fathername" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vatId" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phones" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        defaultValueLiteral="">
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="@OneToMany(fetch=EAGER)&#xD;&#xA;@Fetch(FetchMode.JOIN)"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Action">
    <eLiterals name="Act" literal="Ενέργεια"/>
    <eLiterals name="File" value="1" literal="Αρχείο"/>
    <eLiterals name="None" value="2" literal=""/>
    <eLiterals name="Collaborate" value="3" literal="Συνέργεια"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Document">
    <eOperations name="getCurrentInternalNunber" lowerBound="1"/>
    <eOperations name="cancel" lowerBound="1">
      <eParameters name="handler" eType="#//EntityDescriptor"/>
      <eParameters name="log" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eOperations>
    <eOperations name="close" lowerBound="1">
      <eParameters name="handler" eType="#//EntityDescriptor"/>
      <eParameters name="log" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eOperations>
    <eOperations name="accept" lowerBound="1">
      <eParameters name="handler" eType="#//EntityDescriptor"/>
      <eParameters name="log" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eOperations>
    <eOperations name="forward">
      <eParameters name="owner" eType="#//EntityDescriptor"/>
      <eParameters name="handler" eType="#//EntityDescriptor"/>
      <eParameters name="log" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eOperations>
    <eOperations name="hasBeenThroughThisDirectorateBefore" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean">
      <eParameters name="directorateId" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Short"/>
    </eOperations>
    <eOperations name="allowedOperationsFromThisState" lowerBound="1" upperBound="-1"
        eType="#//DocumentOperations"/>
    <eOperations name="changeState" lowerBound="1">
      <eParameters name="operation" lowerBound="1" eType="#//DocumentOperations"/>
      <eParameters name="logMessage" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eParameters name="handler" lowerBound="1" eType="#//EntityDescriptor"/>
    </eOperations>
    <eOperations name="getOwner" lowerBound="1" eType="#//EntityDescriptor"/>
    <eOperations name="isPending" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eOperations name="isAccepted" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eOperations name="isDone" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//BooleanObject"/>
    <eOperations name="isCancelled" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eOperations name="getState" lowerBound="1" eType="#//DocumentStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="#//UUID"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentstatus" lowerBound="1"
        eType="#//Status" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialstatus" lowerBound="1"
        eType="#//Status" resolveProxies="false">
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="&#xD;&#xA;@Embedded&#xD;&#xA;@AttributeOverrides({&#xD;&#xA;@AttributeOverride(name=&quot;unitId&quot;, column=@Column(name=&quot;initialUnitId&quot;)),   &#xD;&#xA;@AttributeOverride(name=&quot;directorateId&quot;,column=@Column(name=&quot;initialDirectorateId&quot;)),   &#xD;&#xA;@AttributeOverride(name=&quot;internalNumber&quot;, column=@Column(name=&quot;initialInternalNumber&quot;)),   &#xD;&#xA;@AttributeOverride(name=&quot;editorId&quot;, column=@Column(name=&quot;initialEditorId&quot;)),   &#xD;&#xA;@AttributeOverride(name=&quot;handlerId&quot;, column=@Column(name=&quot;initialHandlerId&quot;)) &#xD;&#xA;})"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastDoneDate" lowerBound="1"
        eType="#//LocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastAcceptDate" lowerBound="1"
        eType="#//LocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="physicalLocation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" eType="#//Action"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comments" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="acceptingUnits" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Short"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threadType" lowerBound="1"
        eType="#//ThreadType" defaultValueLiteral="RECIPIENT"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statushistory" lowerBound="1"
        eType="#//StatusHistory"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ThreadType">
    <eLiterals name="RECIPIENT"/>
    <eLiterals name="CC" value="1"/>
    <eLiterals name="COLLABORATION" value="2" literal="COLLABORATION"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Classification">
    <eLiterals name="public" literal="Δημόσιο"/>
    <eLiterals name="internal" value="1" literal="Εσωτερικό"/>
    <eLiterals name="confidential" value="2" literal="Εμπιστευτικό"/>
    <eLiterals name="secret" value="3" literal="Απόρρητο"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Status">
    <eAnnotations source="teneo.jpa">
      <details key="appinfo" value="@Embeddable"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="handler" lowerBound="1"
        eType="#//EntityDescriptor" containment="true" resolveProxies="false">
      <eAnnotations source="teneo.jpa">
        <details key="appInfo" value="@Embedded&#xD;&#xA;@AttributeOverrides({&#xD;&#xA;@AttributeOverride(name=&quot;path&quot;, column=@Column(name=&quot;registeringUnitPath&quot;))&#xD;&#xA;})"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" lowerBound="1"
        eType="#//DocumentStatus" defaultValueLiteral="Σε αναμονή"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1" eType="#//LocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//EntityDescriptor"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="log" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityDescriptor">
    <eOperations name="getLevelName" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eParameters name="level" eType="#//Level"/>
    </eOperations>
    <eOperations name="getLevelId" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Short">
      <eParameters name="level" eType="#//Level"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level" lowerBound="1" upperBound="-1"
        eType="#//Level"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entityId" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Short"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentId" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Short"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PostageInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="postageTime" eType="#//LocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="postageMethod" eType="#//PostalMethod"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="voucherNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String" defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SenderRegistryNumber">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="registryNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="#//LocalDateTime"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegistryRecord">
    <eOperations name="requiresProtocolNumber" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eOperations name="canEdit" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eOperations name="cancel" lowerBound="1">
      <eParameters name="handler" eType="#//EntityDescriptor"/>
      <eParameters name="log" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eOperations>
    <eOperations name="isCancelled" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eOperations name="revert" lowerBound="1">
      <eParameters name="handler" eType="#//EntityDescriptor"/>
      <eParameters name="log" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eOperations>
    <eOperations name="mapToFilepath" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eParameters name="filepath" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attachedFilesDescription"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comments" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subject" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filepaths" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String" defaultValueLiteral="">
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value=" @OneToMany(fetch =EAGER,cascade=CascadeType.ALL)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//DocumentType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="#//UUID"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classification" lowerBound="1"
        eType="#//Classification" defaultValueLiteral="Εσωτερικό"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ada" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        defaultValueLiteral="">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This is the &quot;Αριθμός Διαδικτυακής Ανάρτησης&quot; = ada"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="registrynumber" lowerBound="1"
        eType="#//RegistryNumber" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondent" lowerBound="1"
        upperBound="-1" eType="#//Correspondent" resolveProxies="false">
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value=" @OneToMany(fetch =EAGER)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedNumbers" upperBound="-1"
        eType="#//RegistryNumber"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relatedExternalDocuments"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tags" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegistryNumber">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="registryNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Short"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="#//Year"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1" eType="#//LocalDateTime"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CorespondentType">
    <eLiterals name="RECIPIENT" literal="Παραλήπτης"/>
    <eLiterals name="CC" value="1" literal="Κοινοποίηση"/>
    <eLiterals name="INTERNAL" value="2" literal="Εσωτερική Διανομή"/>
    <eLiterals name="SENDER" value="3" literal="Αποστολέας"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Level">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="levelNumber" eType="#//LevelType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LevelType">
    <eLiterals name="ORGANIZATION" literal="Organization"/>
    <eLiterals name="UNIT" value="1" literal="Unit"/>
    <eLiterals name="SUBUNIT" value="2" literal="Subunit"/>
    <eLiterals name="PERSON" value="4"/>
    <eLiterals name="DEPARTMENT" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="LocalDateTime" instanceClassName="java.util.Date"/>
  <eClassifiers xsi:type="ecore:EDataType" name="UUID" instanceTypeName="newDataType14"/>
  <eClassifiers xsi:type="ecore:EClass" name="Nobody" eSuperTypes="#//EntityDescriptor"/>
</ecore:EPackage>
